name: Bug Issue
description: Report a bug with clear acceptance criteria for when it’s resolved
title: "[BUG]: "
labels: [ bug ]
body:
  - type: input
    id: title
    attributes:
      label: Bug Title
      description: Short title describing the bug
      placeholder: e.g. Product card image fails to load on mobile
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug, including steps to reproduce if possible.
      placeholder: |
        Explain what’s broken, how to reproduce, and expected vs. actual behavior.
        Please include:
        - Device/Browser used
        - Steps to reproduce
        - Expected behavior
        - Actual behavior
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Provide a **checklist** of conditions that define when the bug is fixed.
      placeholder: |
        - [ ] Component renders correctly without errors
        - [ ] Interaction behaves as expected according to requirements
        - [ ] Relevant tests (Vitest/RTL) are passing
        - [ ] No regression in related FSD slices (entities/features)
    validations:
      required: true
