name: Setup Issue
description: Track setup-related tasks with clear acceptance criteria
title: "[Setup]: "
labels: [ setup ]
body:
  - type: input
    id: title
    attributes:
      label: Setup Task Title
      description: Short title for this setup-related issue
      placeholder: e.g. Setup a new feature layer..
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the setup task.
      placeholder: Explain the setup requirement in detail (e.g., adding a new shared component, configuring a provider)...
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Provide a **checklist** of conditions that must be met for setup to be complete.
      placeholder: |
        - [ ] Create necessary FSD layers (shared/entities/features)
        - [ ] Implement core component logic
        - [ ] Add unit tests with Vitest
        - [ ] Verify Tailwind CSS styling
    validations:
      required: true